---

- name: update yum cache
  ansible.builtin.yum:
    update_cache: yes
  become: yes

- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: present
  become: yes

- name: Start and Enable Docker Service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add Jenkins User to Docker Group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes
  become: yes
  notify: Restart Jenkins

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: yes