apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quality
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmd-Sadka/3-tier-todo-devsecops-application.git
    targetRevision: main
    path: Charts/sonarqube
    helm:
      valueFiles:
        - quality-values.yaml
  destination:
    namespace: quality
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    