apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}"
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        {{- toYaml .Values.backend.env | nindent 12 }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}

        # env:
        # - name: MONGO_URI
        #   value: "mongodb://mongo:27017/todos"
        # resources:
        #   requests:
        #     memory: "64Mi"  # Request 64 MiB of memory
        #     cpu: "100m"     # Request 100 milliCPU (0.1 CPU)
        #   limits:
        #     memory: "1Gi"   # Limit memory to 1 GiB
        #     cpu: "1"        # Limit CPU usage to 1 core
