apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-object
spec:
  ingressClassName: nginx
  rules:
  - host: "k8s-default-myreleas-0b6a38b715-0bd88cfa2066b5e3.elb.eu-central-1.amazonaws.com"
    http:
       paths: 
       - pathType: Prefix
         path: /
         backend:
          service:
            name: frontend
            port:
              number: 3000
       - pathType: Prefix
         path: /api
         backend:
          service:
            name: backend
            port:
              number: 3001     
