version: "3.8"

services:
  frontend: 
    build: ./frontend
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api

  backend:
    build: ./backend
    container_name: api
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo:6.0.2
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
