---
- name: "Add the Jenkins GPG Key"
  ansible.builtin.apt_key:
    state: present
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
  become: yes
  #when: ansible_os_family == 'Debian'


- name: "Set Up the Jenkins Repository"
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present
  become: yes

- name: Update apt Cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  #when: ansible_os_family == 'Debian'

- name: "Install Java"
  ansible.builtin.package:
    name: "{{ java_packages }}"
    state: present
  become: yes

- name: "Install Git"
  ansible.builtin.package:
    name: "git"
    state: present
  become: yes

- name: "Install Jenkins"
  ansible.builtin.package:
    name: "{{ jenkins_packages }}"
    state: present
  become: yes

- name: "Start Jenkins"
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes
  become: yes
  notify: Wait for Jenkins to Warm Up