---
- name: lets_go
  hosts: all
  gather_facts: no
  become: yes
  vars_files:
    - secrets/vault.yml
  roles:
    - role: cloudwatchAgent
      tags: [cloudagent, monitoring]

    - role: nodeExp
      tags: [node_exporter, monitoring]

- name: setup_jenkins_and_docker
  hosts: jenkins
  gather_facts: no
  become: yes
  vars_files:
    - secrets/vault.yml
  roles:
    - role: jetkinsCFG
      tags: [jenkins, install, configure, plugins]

    - role: docker
      tags: [docker, install]
